import { startCommandSync } from "./commands";
import { startFaqSync } from "./faq";
import { startWelcomeSync } from "./welcome";
import { startTimers } from "./timers";
import { startModerationSync } from "./moderation";
import { startBetAnnounce } from "./betAnnounce";
import { startEmojiCombo } from "./emojiCombo";
import { startHeartbeat } from "./heartbeat";
import { startTwitch } from "./twitch";
import { startKick } from "./kick";
import { startYouTube } from "./youtube";

console.log("[ghost-empire-chat] starting…");
startCommandSync();
startFaqSync();
startWelcomeSync();
startTimers();
startModerationSync();
startBetAnnounce();
startEmojiCombo();
startHeartbeat();
void startTwitch();
void startKick();
void startYouTube();
